<?php
	echo '<div class="col-md-8 col-md-offset-2">';
	echo '	<div class="row">';
	echo '		<a href="#">';
	echo '			<div id="glownyTematContainer" class="col-md-12">';
	echo '				<img id="glownyTemat" src="img/mirrorsedgepromo.jpg"/>';
	echo '			</div>';
	echo '		</a>';
	echo '	</div>';
	echo '	<div id="glownyRow" class="row">';
	echo '		<div id="glownaTresc" class="col-md-12">';
	echo '			<div class="row text-center">';
	echo '				<div class="hidden-xs col-sm-6 col-md-6 col-lg-4">';
	echo '					<div class="col-md-12 col-lg-12">';
	echo '						<a href="index.php?wyniki=1&rodzaj=battlefront"><div id="promo1" class="minipromo">';
	echo '							<div>';
	echo ' 								<h5>BATTLEFRONT</h5>';
	echo '							</div>';
	echo '						</div></a>';
	echo '					</div>';
	echo '				</div>';
	echo '				<div class="hidden-xs col-sm-6 col-md-6 col-lg-4">';
	echo '					<div class="col-md-12 col-lg-12">';
	echo '						<a href="index.php?wyniki=1&rodzaj=fifa16"><div id="promo2" class="minipromo">';
	echo '							<div>';
	echo ' 								<h5>FIFA 16</h5>';
	echo '							</div>';
	echo '						</div></a>';
	echo '					</div>';
	echo '				</div>';
	echo '				<div class="hidden-xs col-sm-6 col-md-6 col-lg-4">';
	echo '					<div class="col-md-12 col-lg-12">';
	echo '						<a href="index.php?wyniki=1&rodzaj=fallout4"><div id="promo3" class="minipromo">';
	echo '							<div>';
	echo ' 								<h5>Fallout 4</h5>';
	echo '							</div>';
	echo '						</div></a>';
	echo '					</div>';
	echo '				</div>';
	echo '			</div>';
	echo '		</div>';
	echo '	</div>';
	if(@$_SESSION['zalogowano'] != 1)
	{
		echo '				<div id="test" class="row hidden-xs">';
		echo '					<hr class="divider">';
		echo '					<div class="iconbox">';
		echo '						<span class="iconbox-i"><span class="ico i-truck"></span></span>';
		echo '						<h3 class="iconbox-h">Szybka dostawa</h3>';
		echo '						<p class="iconbox-t">Każde zamówienie do godziny 14:00 wysyłane jest jeszcze tego samego dnia.</p>';
		echo '					</div>';
		echo '					<div class="iconbox">';
		echo '						<span class="iconbox-i"><span class="ico i-starproc"></span></span>';
		echo '						<h3 class="iconbox-h">Gwarancja produktu</h3>';
		echo '						<p class="iconbox-t">Gwarantujemy, że każdy produkt trafia do klienta.</p>';
		echo '					</div>';
		echo '					<div class="iconbox">';
		echo '						<span class="iconbox-i"><span class="ico i-prize"></span></span>';
		echo '						<h3 class="iconbox-h">Pozytywne opinie</h3>';
		echo '						<p class="iconbox-t">Nasz serwis znany jest ze 100% pozytywnych opinii.</p>';
		echo '					</div>';
		echo '						<div class="loginbox">';
		echo '							<p><a href="index.php?rejestracja=1" class=""><button class="btn btn-primary" type="button">Załóż konto</button></button></a></p>';
		echo '						</div>';	
		echo '				</div>';		
	}
	else
	{
		echo '				<div id="test" class="row hidden-xs">';
		echo '					<hr class="divider">';
		echo '					<div class="iconboxLog">';
		echo '						<span class="iconbox-i"><span class="ico i-truck"></span></span>';
		echo '						<h3 class="iconbox-h">Szybka dostawa</h3>';
		echo '						<p class="iconbox-t">Każde zamówienie do godziny 14:00 wysyłane jest jeszcze tego samego dnia.</p>';
		echo '					</div>';
		echo '					<div class="iconboxLog">';
		echo '						<span class="iconbox-i"><span class="ico i-starproc"></span></span>';
		echo '						<h3 class="iconbox-h">Gwarancja produktu</h3>';
		echo '						<p class="iconbox-t">Gwarantujemy, że każdy produkt trafia do klienta.</p>';
		echo '					</div>';
		echo '					<div class="iconboxLog">';
		echo '						<span class="iconbox-i"><span class="ico i-prize"></span></span>';
		echo '						<h3 class="iconbox-h">Pozytywne opinie</h3>';
		echo '						<p class="iconbox-t">Nasz serwis znany jest ze 100% pozytywnych opinii.</p>';
		echo '					</div>';	
		echo '				</div>';
	}
	echo ' 				<div class="row" id="dolnyRow"><hr class="divider"></div>';
	echo '</div>';
?>	